[package]
name = "payements-engine"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.93"
csv = "1.3.1"
log = "0.4.22"
rust_decimal = "1.35.0"
serde = { version = "1.0.215", features = ["derive"] }
